version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.20

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run: ./build.sh
      - persist_to_workspace:
          root: ~/repo
          paths: .

  webtests:
    <<: *defaults
    docker:
      - image: cimg/openjdk:17.0-browsers
    environment:
      DISPLAY: :99
      
    steps:
      - run: sudo Xvfb :99 -screen 0 1920x1200x24 > /dev/null 2>&1 &
      - attach_workspace:
          at: ~/repo
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
            ps -efa | grep Xvfb
          name: Check install
      - run: cd webtests && export DISPLAY=:99 && mvn clean install -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver
      - store_artifacts:
          path: ~/repo/webtests/target/surefire-reports
      - store_artifacts:
          path: ~/repo/webtests/target/videos

  docs-deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Add github.com to known hosts
          command: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git config user.email "vankeisb-ci@rvkb.com"
      - run: git config user.name "vankeisb-ci"
      - run:
          name: Deploy docs to gh-pages branch
          command: yarn --cwd sandbox gh-pages

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: ./deploy.sh

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+/
            branches:
              ignore: /gh-pages/
      - webtests:
          requires:
            - build
          filters:
            tags:
              only: /v\d+\.\d+\.\d+/
      - docs-deploy:
          requires:
            - webtests
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - webtests
          filters:
            tags:
              only: /v\d+\.\d+\.\d+/
            branches:
              ignore: /.*/

